FROM jenkins/ssh-slave:latest

# Set Android properties and download zip
ENV ANDROID_SDK_VERSION 25.2.5

ENV ANDROID_SDK_ZIP android-sdk-tools.zip
ENV ANDROID_SDK_ZIP_URL https://dl.google.com/android/repository/tools_r$ANDROID_SDK_VERSION-linux.zip
ENV ANDROID_HOME /opt/android-sdk-linux

ENV PATH $PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools

USER root

# Install android
RUN wget $ANDROID_SDK_ZIP_URL -O /tmp/$ANDROID_SDK_ZIP && \
  mkdir -p $ANDROID_HOME && \
  unzip -q /tmp/$ANDROID_SDK_ZIP -d $ANDROID_HOME && \
  rm /tmp/$ANDROID_SDK_ZIP && \
  mkdir -p ~/.android && touch ~/.android/repositories.cfg && \
  echo y | sdkmanager tools && \
  sdkmanager platform-tools && \
  sdkmanager "platforms;android-25" && \
  sdkmanager "build-tools;27.0.3" && \
  sdkmanager "extras;google;m2repository" && \
  sdkmanager "extras;android;m2repository" && \
  echo y | sdkmanager --licenses && \
  chmod -R 777 $ANDROID_HOME && \
  chown -R jenkins:jenkins $ANDROID_HOME

USER jenkins
